### ISSUE TITLE
Discord link to broken discord

### ISSUE THREAD

**Issue by jkantr** [Jacorb90/Jacorb90.github.io#2]
Okay I guess technically the discord link works, but the check mark button to verify myself to the server to be able to gain access to any channels doesn't work (bot is brokey?) and also it says to message a mod... but anyone i try to message is either a bot or not accepting DMs lol... halp?

EDIT: unless the discord is a patreon only feature? which... would be fine, but it doesn't say that anywhere

**Comment by Jacorb90** [comment]
The problem is probably just carlbot lagging again, so there isn't rlly anything we can do atm other than wait for the servers to stop lagging.
Feel free to message me on discord (Jacorb#8747) so I can manually verify you, or even just the person who sent the most recent message in #verification (they should be accepting DMs).

Thanks for the heads-up :)
